version: '3.4'

services:
  controller:
    image: slurm-swarm-controller:19.05.4
    hostname: controller
    volumes:
      - type: bind
        source:	/new_home/supim-on-docker/shared_volume/
        target: /home/supim-davs/SUPIM-DAVS/
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - slurmnet
    depends_on:
      - worker
#    command: "/usr/sbin/sshd -D"

  worker:
    image: slurm-swarm-worker:19.05.4
    hostname: "worker-{{.Task.Slot}}"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source:	/new_home/supim-on-docker/shared_volume/
        target: /home/supim-davs/SUPIM-DAVS/
    networks:
      - slurmnet
#    command: "/usr/sbin/sshd -D"

networks:
  slurmnet:
    driver: overlay
    attachable: true

#volumes:
#  SUPIM-DAVS-NFS:
#    driver: local
#    driver_opts:
#      type: nfs
#      o: nfsvers=4,addr=controller,rw
#      device: ":/var/lib/docker/volumes/SUPIM-DAVS/_data"
