version: '3.4'

services:
  controller:
    image: slurm-swarm-controller:19.05.4
    container_name: slurm_controller
    hostname: controller
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - slurmnet
    depends_on:
      - worker
#    command: "/usr/sbin/sshd -D"

  worker:
    image: slurm-swarm-worker:19.05.4
    hostname: "worker-{{.Task.Slot}}"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - slurmnet
#    command: "/usr/sbin/sshd -D"

networks:
  slurmnet:
    driver: overlay
    attachable: true
